config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :user
  
  resources :device_packs
  resources :experience_packs
  resources :companies
  resources :meetings

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord

  enum package: [:bronze, :silver, :gold, :platinum]

  validates :name, :host, presence: true
end

app/models/concerns/duration.rb
module Duration
  DURATIONS = {"5 minutes": "00:05:00", "10 minutes": "00:10:00", "20 minutes": "00:20:00", "30 minutes": "00:30:00", "40 minutes": "00:40:00", "50 minutes": "00:50:00", "1 hour": "01:00:00"}
end

app/models/device_pack.rb
class DevicePack < ApplicationRecord
end

app/models/experience_pack.rb
class ExperiencePack < ApplicationRecord
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  include Duration

  validates :topic, :password, presence: true
  
  belongs_to :user
  belongs_to :device_pack
  has_many :meeting_experience_packs
  has_many :experience_packs, through: :meeting_experience_packs

  scope :completed, ->(user) { where("start_time < ? and user_id = ?", Date.today, user.id) }
  scope :upcoming, ->(user) { where("start_time >= ? and user_id = ?", Time.now, user.id)} 
  scope :earlier, -> { where("start_time < ?", Date.today) }
end

app/models/meeting_experience_pack.rb
class MeetingExperiencePack < ApplicationRecord
  belongs_to :meeting
  belongs_to :experience_pack
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attr_accessor :skip_some_callbacks

  validates :user_name, presence: true, uniqueness: true
  
  before_validation :set_password
  skip_callback :validation, :before, :set_password, unless: :skip_some_callbacks

  scope :current_user_except, -> (user) { where.not(id: user) } 

  private
    def set_password 
      self.password = SecureRandom.hex(4)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :company_name, :user_name])
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to companies_path
    else
      render :new
    end
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])

    if @company.update(company_params)
      redirect_to companies_path
    else
      render :edit
    end
  end

  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    redirect_to companies_path
  end

  private
    def company_params
      params.require(:company).permit(:name, :host, :package)
    end
end

app/controllers/device_packs_controller.rb
class DevicePacksController < ApplicationController
  before_action :authenticate_user!
  def index
    @device_packs = DevicePack.all
  end

  def new
    @device_pack = DevicePack.new
  end

  def create
    @device_pack = DevicePack.new(device_pack_params)
    if @device_pack.save
      redirect_to device_packs_path
    else
      render :new
    end
  end

  def edit
    @device_pack = DevicePack.find(params[:id])
  end

  def update
    @device_pack = DevicePack.find(params[:id])
    if @device_pack.update(device_pack_params)
      redirect_to device_packs_path
    else
      render :edit
    end
  end

  def destroy
    @device_pack = DevicePack.find(params[:id])
    @device_pack.destroy
    redirect_to device_packs_path
  end

  private
    def device_pack_params
      params.require(:device_pack).permit(:name)
    end
end

app/controllers/experience_packs_controller.rb
class ExperiencePacksController < ApplicationController
  before_action :authenticate_user!
  def index
    @experience_packs = ExperiencePack.all
  end

  def new
    @experience_pack = ExperiencePack.new
  end

  def create
    @experience_pack = ExperiencePack.new(experience_pack_params)
    if @experience_pack.save
      redirect_to experience_packs_path
    else
      render :new
    end
  end

  def edit
    @experience_pack = ExperiencePack.find(params[:id])
  end

  def update
    @experience_pack = ExperiencePack.find(params[:id])
    if @experience_pack.update(experience_pack_params)
      redirect_to experience_packs_path
    else
      render :edit
    end
  end

  def destroy
    @experience_pack = ExperiencePack.find(params[:id])
    @experience_pack.destroy
    redirect_to experience_packs_path
  end

  private
    def experience_pack_params
      params.require(:experience_pack).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index

  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :authenticate_user!
  def index
    if params[:meeting_type] == "completed"
      @meetings = Meeting.completed(current_user)
      @meetings = @meetings.where(start_time: params[:start_date]..params[:end_date]) if request.xhr?
    else  
      @meetings = Meeting.upcoming(current_user)
      @meetings = @meetings.where(start_time: params[:start_date]..params[:end_date]) if request.xhr?
    end
  end

  def new
    @meeting = Meeting.new
  end

  def create
    @meeting = Meeting.new(meeting_params.merge(user_id: current_user.id))
    if @meeting.save
      redirect_to meetings_path
    else
      render :new
    end
  end

  def edit
    @meeting = Meeting.find(params[:id])
  end

  def update
    @meeting = Meeting.find(params[:id])
    if @meeting.update(meeting_params)
      redirect_to meetings_path
    else
      render :edit
    end
  end

  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy
    redirect_to meetings_path
  end

  private
    def meeting_params
      params.require(:meeting).permit(:topic, :password, :start_time, :duration, :time_zone, :device_pack_id, :alternate_host, experience_pack_ids: [], attendees: [])
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.current_user_except(current_user)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.skip_some_callbacks = true
    if @user.save
      redirect_to user_index_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_index_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to user_index_path
  end

  private
    def user_params
      params.require(:user).permit(:user_name, :email, :user_id, :company_name, :password, :password_confirmation, :skip_some_callbacks)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/_form.html.erb
<div class="card-body">
  <%= form_with model: company do |f| %>
    <div class="form-group">
      <%= f.text_field :name, placeholder: 'Company Name', class: 'form-control' %>
    </div><br>

    <div class="form-group">
      <%= f.text_field :host, placeholder: 'Host', class: 'form-control' %>
    </div><br>

    <div class="form-group">
      <label class="form-label">Package</label>
      <%= f.select :package, Company.packages.keys, {}, {class: "form-control"} %>
    </div><br>

    <div class="actions">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/companies/edit.html.erb
<div class="card mt-4">
  <div class="card-header">Edit Company</div>
  <%= render "form", company: @company %>
</div>

app/views/companies/index.html.erb
<div class= 'row mt-4'>
  <div class='col-md-6'>
    <h3>Companies</h3>
  </div>
  <div class='col-md-6'>
    <div class="float-end">
      <%= link_to ' + Add Company ', new_company_path , class: 'btn btn-primary'%>
    </div>
  </div>
  </br>
  </br>
  </br>
  <div class="table-responsive col-md-12">
    <table id="example" class="table table-striped" style="width:100%">
      <thead>
        <tr>
          <th>Company name</th>
          <th>Host</th>
          <th>Subscription plan</th>
          <th>No. of users</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @companies.each do |company| %>
          <tr>
            <td><%= company.name %></td>
            <td><%=  company.host %></td>
            <td><%=  company.package %></td>
            <td></td>
            <td><%#= link_to "<i class='far fa-eye'></i>".html_safe,company_path(company) %><%= link_to "<i class='far fa-edit'></i>".html_safe,edit_company_path(company) %>&nbsp;&nbsp; <%= link_to "<i class='far fa-trash-alt'></i>".html_safe, company_path(company), method: :delete, data: { confirm: "Are you sure?" } %></td>
          </tr>
        <% end %>  
      </tbody>
      <!-- <tfoot>
        <tr>
          <th>Name</th>
          <th>Host</th>
          <th>Package</th>
          <th></th>
        </tr>
      </tfoot> -->
    </table>
  </div>
</div>

<script>
  $(document).ready(function() {
    $('#example').DataTable();
  } );
</script> 

app/views/companies/new.html.erb
<div class="card mt-4">
  <div class="card-header">Add Company</div>
  <%= render "form", company: @company %>
</div>

app/views/companies/show.html.erb
<div class="card mt-4">
  <div class="card-header">
    Company Details
  </div>
  <div class="card-body">
    <b>Name: </b><span><%= @company.name%></span><br>
    <b>Host: </b><span><%= @company.host%></span><br>
    <b>Package: </b><span><%= @company.package%></span><br><br>
    <%= link_to "Back", companies_path %>  
  </div>
</div>

app/views/device_packs/_form.html.erb
<div class="card-body">
  <%= form_with model: @device_pack do |f| %>
    <div class="form-group">
      <%= f.text_field :name, placeholder: 'Experience Name', class: 'form-control' %>
    </div><br>

    <div class="actions">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/device_packs/edit.html.erb
<div class="card mt-4">
  <div class="card-header">Edit Device Pack</div>
  <%= render "form" %>
</div>

app/views/device_packs/index.html.erb
<div class= 'row mt-4'>
  <div class='col-md-6'>
    <h3>Devices</h3>
  </div>
  <div class='col-md-6'>
    <div class="float-end">
      <%= link_to ' + Add device pack ', new_device_pack_path , class: 'btn btn-primary'%>
    </div>
  </div>
  </br>
  </br>
  </br>
  <div class="table-responsive col-md-12">
    <table id="example" class="table table-striped" style="width:100%">
      <thead>
        <tr>
          <th>Device name</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @device_packs.each do |device| %>
          <tr>
            <td><%= device.name %></td>
            <td><%#= link_to "<i class='far fa-eye'></i>".html_safe,company_path(company) %><%= link_to "<i class='far fa-edit'></i>".html_safe,edit_device_pack_path(device) %>&nbsp;&nbsp; <%= link_to "<i class='far fa-trash-alt'></i>".html_safe, device_pack_path(device), method: :delete, data: { confirm: "Are you sure?" } %></td>
          </tr>
        <% end %>  
      </tbody>
      <!-- <tfoot>
        <tr>
          <th>Name</th>
          <th>Host</th>
          <th>Package</th>
          <th></th>
        </tr>
      </tfoot> -->
    </table>
  </div>
</div>

<script>
  $(document).ready(function() {
    $('#example').DataTable();
  } );
</script> 

app/views/device_packs/new.html.erb
<div class="card mt-4">
  <div class="card-header">New Device Pack</div>
  <%= render "form" %>
</div>

app/views/experience_packs/_form.html.erb
<div class="card-body">
  <%= form_with model: @experience_pack do |f| %>
    <div class="form-group">
      <%= f.text_field :name, placeholder: 'Experience Name', class: 'form-control' %>
    </div><br>

    <div class="actions">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/experience_packs/edit.html.erb
<div class="card mt-4">
  <div class="card-header">Edit Experience Pack</div>
  <%= render "form" %>
</div>

app/views/experience_packs/index.html.erb
<div class= 'row mt-4'>
  <div class='col-md-6'>
    <h3>Experiences</h3>
  </div>
  <div class='col-md-6'>
    <div class="float-end">
      <%= link_to ' + Add experience pack ', new_experience_pack_path , class: 'btn btn-primary'%>
    </div>
  </div>
  </br>
  </br>
  </br>
  <div class="table-responsive col-md-12">
    <table id="example" class="table table-striped" style="width:100%">
      <thead>
        <tr>
          <th>Experience name</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @experience_packs.each do |experience| %>
          <tr>
            <td><%= experience.name %></td>
            <td><%#= link_to "<i class='far fa-eye'></i>".html_safe,company_path(company) %><%= link_to "<i class='far fa-edit'></i>".html_safe,edit_experience_pack_path(experience) %>&nbsp;&nbsp; <%= link_to "<i class='far fa-trash-alt'></i>".html_safe, experience_pack_path(experience), method: :delete, data: { confirm: "Are you sure?" } %></td>
          </tr>
        <% end %>  
      </tbody>
      <!-- <tfoot>
        <tr>
          <th>Name</th>
          <th>Host</th>
          <th>Package</th>
          <th></th>
        </tr>
      </tfoot> -->
    </table>
  </div>
</div>

<script>
  $(document).ready(function() {
    $('#example').DataTable();
  } );
</script> 

app/views/experience_packs/new.html.erb
<div class="card mt-4">
  <div class="card-header">New Experience Pack</div>
  <%= render "form" %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="#">Clear-Connect</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <%if user_signed_in?%>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <%= link_to "Companies", companies_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Users", user_index_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Experience Pack", experience_packs_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Device Pack", device_packs_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Meetings", meetings_path, class: 'nav-link' %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.email %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><%= link_to 'Edit Profile', edit_user_registration_path, class: 'dropdown-item' %></li>
              <li><%= link_to 'SignOut', destroy_user_session_path, method: 'delete', class: 'dropdown-item' %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClearConnect</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
    
    
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs5/jq-3.6.0/dt-1.11.3/datatables.min.css"/>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs5/jq-3.6.0/dt-1.11.3/datatables.min.js"></script>



    <!-- Daterange picker js -->
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    
    <!-- Daterange picker css -->
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
  </head>

  <body>
    <%= render partial: "layouts/header" %>

    <div class="container">     
      <%= yield %>

      <footer>
        <!-- <p>&copy; Company 2020</p> -->
      </footer>
    </div> 

    
  </body>
</html>

app/views/meetings/_filter.html.erb
<div class="dropdown">
  <button class="btn dropdown-toggle border-dark" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false"><i class="fa fa-search"></i>&nbsp;&nbsp;My Meetings</button>

  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <li><a class="dropdown-item" href="#">Action</a></li>
    <li><a class="dropdown-item" href="#">Another action</a></li>
    <li><a class="dropdown-item" href="#">Something else here</a></li>
  </ul>&nbsp;&nbsp;&nbsp;

  <input type="button" class="btn border-dark meeting_daterange" name="daterange" value="01/01/2030 - 31/01/2030" />
  &nbsp;&nbsp;&nbsp;

  <input type="checkbox" class="checkbox" id="meeting" name="meeting" value="Meeting"> Show earlier meetings
</div>

<div class="table-responsive col-md-12 default_meetings">
  <table id="example" class="table table-striped" style="width:100%">
    <thead>
      <tr>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody class= "meeting-table">
      <%=render partial: 'table' %>
    </tbody>
  </table>
</div>

app/views/meetings/_form.html.erb
<div class="card-body">
  <%= form_with model: @meeting, local: true do |f| %>
    <div class="form-group">
      <%= f.text_field :topic, placeholder: 'Meeting Topic *', class: 'form-control' %>
    </div><br>

    <div class="form-group">
      <%= f.text_field :password, placeholder: 'Meeting Password *', class: 'form-control' %>
    </div><br>

    <div class="form-group">
      <%= f.datetime_field :start_time, as: :datetime_picker, placeholder: 'Date and Time', class: 'form-control' %>
    </div><br>

    <div class="form-group">
      <%= f.select :duration, Meeting::DURATIONS, {prompt: 'Duration'}, {class: "form-control"}  %>
    </div><br>

    <div class="form-group">
      <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, { include_blank: 'Time Zone' }, { required: true, class: 'form-control' } %>
    </div><br>

    <div class="form-group">
      <label class="form-label">VR Experiences: </label>&nbsp;&nbsp;&nbsp;
      <% ExperiencePack.all.each do |exp| %>
        <label>
          <%= check_box_tag "meeting[experience_pack_ids][]", exp.id, class: 'form-control'%>
          <%= exp.name %>
        </label>
      <% end %>
    </div><br>

    <div class="form-group">
      <%= f.select :device_pack_id, DevicePack.all.map{|c| [c.name, c.id]}, {prompt: 'Select Device Pack'}, {class: "form-control"} %>
    </div><br>

    <div class="form-group">
      <%= f.email_field :attendees, multiple: true, :placeholder => 'Seperate email addresses with a comma or semicolon', :class => 'form-control'  %>
    </div><br>

    <div class="form-group">
      <%= f.text_field :alternate_host, placeholder: 'Alternate Host', class: 'form-control' %>
    </div><br>

    <div class="actions">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/meetings/_tab.html.erb
<% upcoming = params[:meeting_type] == 'upcomming' ? 'active' : '' %>
<% complete = params[:meeting_type] == 'completed' ? 'active' : '' %>

<% if (params[:view_type] == "calendar" && params[:meeting_type] == "completed") || (params[:view_type] == "calendar" && params[:meeting_type] == "upcomming") %>
  <%= link_to 'Upcoming', meetings_path(meeting_type: 'upcomming', view_type: 'calendar'), class: "d-inline-block link-secondary fs-4 px-2 upcoming relative #{upcoming}", style: 'text-decoration: none'%>  
  <%= link_to 'Completed', meetings_path(meeting_type: 'completed', view_type: 'calendar'), class: "link-secondary fs-4 px-2 completed d-inline-block mr-2 relative  #{complete}", style: 'text-decoration: none'%>
<% else %>
  <%= link_to 'Upcoming', meetings_path(meeting_type: 'upcomming'), class: "d-inline-block px-2 link-secondary fs-4 upcoming relative #{upcoming}", style: 'text-decoration: none'%>
  <%= link_to 'Completed', meetings_path(meeting_type: 'completed'), class: "d-inline-block px-2  link-secondary fs-4 completed relative #{complete}", style: 'text-decoration: none'%>
<% end %>



<div class="float-end">
  <% if params[:meeting_type] == "completed" || (params[:view_type] == "list" && params[:meeting_type] == "completed") || (params[:view_type] == "calendar" && params[:meeting_type] == "completed") %>
    <%= link_to "<i class='fas fa-list'></i>".html_safe, meetings_path(view_type: 'list',meeting_type: 'completed'), class: "link-secondary fs-4" %>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <%= link_to "<i class='far fa-calendar-alt calendar-class'></i>".html_safe, meetings_path(view_type: 'calendar',meeting_type: 'completed'), class: "link-secondary fs-4" %>
  <% else %>
    <%= link_to "<i class='fas fa-list'></i>".html_safe, meetings_path(view_type: 'list', meeting_type: 'upcomming'), class: "link-secondary fs-4" %>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <%= link_to "<i class='far fa-calendar-alt calendar-class'></i>".html_safe, meetings_path(view_type: 'calendar', meeting_type: 'upcomming'), class: "link-secondary fs-4" %>
  <% end %>
</div>
<hr>

app/views/meetings/_table.html.erb
 <% @meetings.each do |meet| %>
  <tr>
    <td>
      <%= meet.start_time.strftime('%I:%M %p') %> - <%= (meet.start_time + meet.duration.strftime("%H").to_i.hour + meet.duration.strftime("%M").to_i.minute).strftime('%I:%M %p')%>
      <br>
      <%=  meet.start_time.strftime("%a, %b #{meet.start_time.day}") %>
    </td>
    <td>
      <%= meet.topic %>
      <br>
      <%= meet.user.full_name%>
    </td>
    <td>
      <%= link_to "<i class='far fa-edit'></i>".html_safe,edit_meeting_path(meet) %>
      &nbsp;&nbsp; 
      <%= link_to "<i class='far fa-trash-alt'></i>".html_safe, meeting_path(meet), method: :delete, data: { confirm: "Are you sure?" } %>
    </td>
  </tr>
<% end %>  

app/views/meetings/index.html.erb
<div class="bg-white ">
  <div class= 'row mt-4'>
    <div class='col-md-6'>
      <h3 class="fs-2">My Meetings</h3>
    </div>

    <div class='col-md-6'>
      <div class="float-end">
        <%= link_to ' + Schedule a Meeting', new_meeting_path , class: 'btn btn-primary'%>
      </div>
    </div>
  </div>
</div>
<div class="bg-light p-3 pt-4">
  <%=render partial: 'tab' %>

  <% if (params[:meeting_type] == "completed" && params[:view_type] == "calendar") || (params[:meeting_type] == "upcomming" && params[:view_type] == "calendar") %>
    <div id="calendar"></div>
  <% else %>
    <%=render partial: 'filter' %>
<% end %>
</div>



<%= javascript_pack_tag 'calendar' %>
<script>
  $(function() {
    $('.meeting_daterange').daterangepicker({
      locale: {
        format: 'DD/MM/YYYY'
      }
    },
    function(start, end, label) {
      var type_var = "<%= params[:meeting_type] %>"
      $.ajax({
        type: "GET",// GET in place of POST
        contentType: "application/json; charset=utf-8",
        url: "/meetings",
        data : {start_date: start.format('YYYY-MM-DD'), end_date: end.format('YYYY-MM-DD'), meeting_type: type_var},
        dataType: "script"
      });
    });
  });
</script>

app/views/user/edit.html.erb
<div class="card mt-4">
  <div class="card-header">Edit User</div>
    <%= render partial: "form", locals: { url_path: user_path(@user)} %>
  </div>
</div>

app/views/user/index.html.erb
<div class= 'row mt-5'>
  <div class='col-md-6'>
    <h3>User management</h3>
  </div>
  <div class='col-md-6'>
    <div class="float-end">
      <%= link_to "+ Add User", new_user_path, class: 'btn btn-primary' %>
    </div>
  </div>
  </br>
  </br>
  </br>
  <div class="table-responsive col-md-12">
    <table id="example" class="table table-striped" style="width:100%">
      <thead>
        <tr>
          <th>User Name</th>
          <th>Email</th>
          <th>Host</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr class="border">
            <td><%= user.user_name %></td>
            <td><%=  user.email %></td>
            <td>Yes</td>
            <td><%#= link_to "<i class='far fa-eye'></i>".html_safe,user_path(user) %><%= link_to "<i class='far fa-edit'></i>".html_safe,edit_user_path(user) %>&nbsp;&nbsp; <%= link_to "<i class='fas fa-trash-alt'></i>".html_safe, user_path(user),
                    method: :delete,
                    data: { confirm: "Are you sure?" } %>
            </td>
          </tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <th>User Name</th>
          <th>Email</th>
          <th>Company Name</th>
          <th></th>
        </tr>
      </tfoot>
    </table>
  </div>
</div>

<script>
  $(document).ready(function() {
    $('#example').DataTable();
  });
</script> 